# Default values for echo-server.
namespace:
  name: echo-server
  create: true

image:
  repository: goldraven/echo-server
  tag: latest
  pullPolicy: Always

dockerRegistry:
  enabled: true
  server: https://index.docker.io/v1/
  username: goldraven
  password: Razvilka1+2
  email: your-email@example.com

deployment:
  replicas: 3
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  env:
    AUTHOR: "Kubernetes Helm Deployment"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: echo.example.com
      paths:
        - path: /
          pathType: Prefix
