apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: echo-server
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJnb2xkcmF2ZW4iLCJwYXNzd29yZCI6IlJhenZpbGthMSsyIiwiZW1haWwiOiJ5b3VyLWVtYWlsQGV4YW1wbGUuY29tIiwiYXV0aCI6IloyOXNaSEpoZG1WdU9sSmhlblpwYkd0aE1Tc3kifX19
